"""Apply the final academic-review wording fixes to the generated notebook.

The notebook is first generated by ``build_final_notebook.py``.  This small
post-processing step keeps the generated artifact scientifically aligned with
the final report without touching any numerical output or experimental result.
"""

from pathlib import Path

import nbformat


NOTEBOOK = Path(__file__).resolve().parent / "HMM_Market_Regimes_Project.ipynb"


REPLACEMENTS = {
    "הנתונים התבקשו לטווח `2014-01-01` עד `2024-12-31`. החלוקה כרונולוגית: כ-70% Train, כ-15% Validation וכ-15% Test. שורות גבול שבהן יעד היום הבא חוצה partition הוסרו, וכל scaling מותאם על Train בלבד.":
    "הנתונים התבקשו לטווח `2014-01-01` עד `2024-12-31`. זהו חלון הבקשה המשותף; זמינות התצפיות בפועל שונה מעט בין נכסים, ובפרט `BTC-USD` מתחיל מאוחר יותר. כל split מחושב מתוך התצפיות הזמינות בפועל לכל נכס. החלוקה כרונולוגית: כ-70% Train, כ-15% Validation וכ-15% Test. שורות גבול שבהן יעד היום הבא חוצה partition הוסרו, וכל scaling מותאם על Train בלבד.",

    "בנוסף ל-hard state נבדק soft posterior, המשתמש בכל \\(P(S_t=k\\mid X_{1:T})\\). כך יום שבו המודל מתלבט בין שני states אינו מטופל כאילו הוא שייך בוודאות ל-state יחיד.":
    "בנוסף ל-hard state נבדק soft posterior. בהערכת Test ה-inference הוא past-only: עבור יום \\(t\\) משתמשים ב-\\(P(S_t=k\\mid X_{1:t})\\), ללא תצפיות עתידיות מתוך ה-Test. כך יום שבו המודל מתלבט בין שני states אינו מטופל כאילו הוא שייך בוודאות ל-state יחיד, ובמקביל נשמרת סיבתיות התחזית ליום הבא.",

    "זהו אחד הממצאים החזקים בעבודה: posterior confidence ממוצע ב-SPY הוא כ-96.6%, אבל entropy בימי switch עולה לכ-0.307 לעומת כ-0.054 בימים ללא switch. המתאם שלה עם absolute return או rolling volatility כמעט אפסי. לכן entropy אינה פשוט proxy לתנודתיות; היא מתארת בעיקר **אי-ודאות לגבי גבול בין regimes**.":
    "posterior confidence ממוצע ב-SPY הוא כ-96.6%, אבל entropy בימי switch עולה לכ-0.307 לעומת כ-0.054 בימים ללא switch. זהו diagnostic שימושי של ambiguity, אך חשוב לפרש אותו בזהירות: hard switch מוגדר משינוי ב-argmax של אותו posterior, ולכן צפוי במידה מסוימת שימים ליד הגבול יהיו גם בעלי entropy גבוהה יותר. המתאם של entropy עם absolute return או rolling volatility כמעט אפסי, ולכן היא אינה פשוט proxy לתנודתיות. הקשר ל-switch מוצג כאן כמדד פנימי של confidence ולא כ-validation חיצוני עצמאי.",

    "ב-State 3 הקורלציה עם SPY מגיעה לכ-0.98 ב-QQQ, 0.77 ב-HYG, 0.63 ב-BTC-USD, 0.68 ב-JPM ו-0.77 ב-NVDA. לעומת זאת TLT נמצא באותו state בקורלציה קרובה לאפס ואף מעט שלילית. מכאן עולה שה-HMM אינו רק \"צובע\" את SPY; חלק מה-states מתלווים גם לשינוי במבנה התלות בין asset classes.":
    "ב-State 3 הקורלציה עם SPY מגיעה לכ-0.98 ב-QQQ, 0.77 ב-HYG, 0.63 ב-BTC-USD, 0.68 ב-JPM ו-0.77 ב-NVDA. לעומת זאת TLT נמצא באותו state בקורלציה קרובה לאפס ואף מעט שלילית. זה תומך בכך שחלק מה-states מתלווים לשינוי במבנה התלות בין asset classes, אך זהו ניתוח תיאורי: בתקופת החפיפה היו 325 ימים ב-State 0, רק 41 ב-State 1 ו-46 ב-State 3, ו-State 2 לא הופיע. לכן אין כאן טענת מובהקות או סיבתיות.",
}


def main() -> None:
    if not NOTEBOOK.exists():
        raise FileNotFoundError(
            f"{NOTEBOOK.name} does not exist; run build_final_notebook.py first"
        )

    nb = nbformat.read(NOTEBOOK, as_version=4)
    applied = {old: 0 for old in REPLACEMENTS}

    for cell in nb.cells:
        if cell.cell_type != "markdown":
            continue
        for old, new in REPLACEMENTS.items():
            if old in cell.source:
                cell.source = cell.source.replace(old, new)
                applied[old] += 1

    missing = [old for old, count in applied.items() if count != 1]
    if missing:
        details = {old[:70]: applied[old] for old in missing}
        raise RuntimeError(f"Notebook patch did not match exactly once: {details}")

    nbformat.write(nb, NOTEBOOK)
    print(f"Patched {NOTEBOOK.name}: {len(REPLACEMENTS)} academic-review replacements")


if __name__ == "__main__":
    main()
