"""Apply final academic-review fixes to the generated notebook.

The notebook is first generated by ``build_final_notebook.py``. This post-processing
step keeps the executed submission scientifically aligned with the final report,
without changing any experimental result or retraining a model.
"""

from pathlib import Path
import textwrap

import nbformat


NOTEBOOK = Path(__file__).resolve().parent / "HMM_Market_Regimes_Project.ipynb"


REPLACEMENTS = {
    "הנתונים התבקשו לטווח `2014-01-01` עד `2024-12-31`. החלוקה כרונולוגית: כ-70% Train, כ-15% Validation וכ-15% Test. שורות גבול שבהן יעד היום הבא חוצה partition הוסרו, וכל scaling מותאם על Train בלבד.":
    "הנתונים התבקשו לטווח `2014-01-01` עד `2024-12-31`. זהו חלון הבקשה המשותף; זמינות התצפיות בפועל שונה מעט בין נכסים, ובפרט `BTC-USD` מתחיל מאוחר יותר. כל split מחושב מתוך התצפיות הזמינות בפועל לכל נכס. החלוקה כרונולוגית: כ-70% Train, כ-15% Validation וכ-15% Test. שורות גבול שבהן יעד היום הבא חוצה partition הוסרו, וכל scaling מותאם על Train בלבד.",

    "בנוסף ל-hard state נבדק soft posterior, המשתמש בכל \\(P(S_t=k\\mid X_{1:T})\\). כך יום שבו המודל מתלבט בין שני states אינו מטופל כאילו הוא שייך בוודאות ל-state יחיד.":
    "בנוסף ל-hard state נבדק soft posterior. בהערכת Test ה-inference הוא past-only: עבור יום \\(t\\) משתמשים ב-\\(P(S_t=k\\mid X_{1:t})\\), ללא תצפיות עתידיות מתוך ה-Test. כך יום שבו המודל מתלבט בין שני states אינו מטופל כאילו הוא שייך בוודאות ל-state יחיד, ובמקביל נשמרת סיבתיות התחזית ליום הבא.",

    "זהו אחד הממצאים החזקים בעבודה: posterior confidence ממוצע ב-SPY הוא כ-96.6%, אבל entropy בימי switch עולה לכ-0.307 לעומת כ-0.054 בימים ללא switch. המתאם שלה עם absolute return או rolling volatility כמעט אפסי. לכן entropy אינה פשוט proxy לתנודתיות; היא מתארת בעיקר **אי-ודאות לגבי גבול בין regimes**.":
    "posterior confidence ממוצע ב-SPY הוא כ-96.6%, אבל entropy בימי switch עולה לכ-0.307 לעומת כ-0.054 בימים ללא switch. זהו diagnostic שימושי של ambiguity, אך חשוב לפרש אותו בזהירות: hard switch מוגדר משינוי ב-argmax של אותו posterior, ולכן צפוי במידה מסוימת שימים ליד הגבול יהיו גם בעלי entropy גבוהה יותר. המתאם של entropy עם absolute return או rolling volatility כמעט אפסי, ולכן היא אינה פשוט proxy לתנודתיות. הקשר ל-switch מוצג כאן כמדד פנימי של confidence ולא כ-validation חיצוני עצמאי.",

    "ב-State 3 הקורלציה עם SPY מגיעה לכ-0.98 ב-QQQ, 0.77 ב-HYG, 0.63 ב-BTC-USD, 0.68 ב-JPM ו-0.77 ב-NVDA. לעומת זאת TLT נמצא באותו state בקורלציה קרובה לאפס ואף מעט שלילית. מכאן עולה שה-HMM אינו רק \"צובע\" את SPY; חלק מה-states מתלווים גם לשינוי במבנה התלות בין asset classes.":
    "ב-State 3 הקורלציה עם SPY מגיעה לכ-0.98 ב-QQQ, 0.77 ב-HYG, 0.63 ב-BTC-USD, 0.68 ב-JPM ו-0.77 ב-NVDA. לעומת זאת TLT נמצא באותו state בקורלציה קרובה לאפס ואף מעט שלילית. זה תומך בכך שחלק מה-states מתלווים לשינוי במבנה התלות בין asset classes, אך זהו ניתוח תיאורי: בתקופת החפיפה היו 325 ימים ב-State 0, רק 41 ב-State 1 ו-46 ב-State 3, ו-State 2 לא הופיע. לכן אין כאן טענת מובהקות או סיבתיות.",

    "בממוצע בין תשעת הנכסים: Naive train-mean משיג כ-54.54% DPA, Logistic Regression כ-54.14%, Random Forest כ-53.27%, HMM soft-posterior כ-53.06%, HistGradientBoosting כ-52.49% ו-HMM hard-state כ-52.06%.\n\nיש הצלחות מקומיות, למשל Random Forest ב-QQQ וב-BTC-USD ו-soft HMM ב-QQQ, אבל אין מודל שמנצח באופן עקבי. לכן אין בסיס לטענה שה-HMM מספק predictive edge יציב.":
    "בממוצע בין תשעת הנכסים: Naive train-mean משיג כ-54.54% DPA, Logistic Regression כ-54.14%, Discrete Markov Chain כ-53.90%, Random Forest כ-53.27%, HMM soft-posterior כ-53.06%, HistGradientBoosting כ-52.49%, HMM hard-state כ-52.06%, Naive persistence כ-50.45% ו-Moving Average 5 כ-50.27%.\n\nיש הצלחות מקומיות, למשל Random Forest ב-QQQ וב-BTC-USD ו-soft HMM ב-QQQ, אבל אין מודל שמנצח באופן עקבי. הצגת כל ה-Baselines חשובה במיוחד משום ש-Discrete Markov Chain הפשוט נמצא בממוצע מעל שני ה-HMM variants. לכן אין בסיס לטענה שה-HMM מספק predictive edge יציב.",
}


def rtl_md(text: str):
    text = textwrap.dedent(text).strip()
    return nbformat.v4.new_markdown_cell(f'<div dir="rtl">\n\n{text}\n\n</div>')


def code_cell(text: str):
    return nbformat.v4.new_code_cell(textwrap.dedent(text).strip())


def find_markdown_index(nb, needle: str) -> int:
    matches = [
        i for i, cell in enumerate(nb.cells)
        if cell.cell_type == "markdown" and needle in cell.source
    ]
    if len(matches) != 1:
        raise RuntimeError(f"Expected one markdown cell containing {needle!r}, got {matches}")
    return matches[0]


def main() -> None:
    if not NOTEBOOK.exists():
        raise FileNotFoundError(
            f"{NOTEBOOK.name} does not exist; run build_final_notebook.py first"
        )

    nb = nbformat.read(NOTEBOOK, as_version=4)
    applied = {old: 0 for old in REPLACEMENTS}

    for cell in nb.cells:
        if cell.cell_type != "markdown":
            continue
        for old, new in REPLACEMENTS.items():
            if old in cell.source:
                cell.source = cell.source.replace(old, new)
                applied[old] += 1

    missing = [old for old, count in applied.items() if count != 1]
    if missing:
        details = {old[:70]: applied[old] for old in missing}
        raise RuntimeError(f"Notebook patch did not match exactly once: {details}")

    # The original generated comparison focused on the headline methods and omitted
    # three pre-specified simple baselines. Keep the same verified artifacts but
    # report all planned baselines in the notebook summary table.
    comparison_cells = [
        cell for cell in nb.cells
        if cell.cell_type == "code" and "models_for_mean =" in cell.source
    ]
    if len(comparison_cells) != 1:
        raise RuntimeError("Could not identify the mean-DPA comparison code cell")
    comparison_cells[0].source = textwrap.dedent(r'''
        hmm_metrics = pd.read_csv(EXTENDED_RUN / "test_metrics_all_assets.csv")
        mean_hmm = (
            hmm_metrics.groupby("model", as_index=False)["DPA_direction_accuracy"]
            .mean()
        )
        supervised_summary = (
            pd.read_csv(SUPERVISED_RUN / "supervised_summary.csv")
            .rename(columns={"mean_DPA_direction_accuracy": "DPA_direction_accuracy"})
            [["model", "DPA_direction_accuracy"]]
        )
        mean_comparison = pd.concat([mean_hmm, supervised_summary], ignore_index=True)

        expected_models = {
            "Naive - train mean", "Naive - persistence", "Moving Average 5",
            "Discrete Markov Chain", "Gaussian HMM - hard state",
            "Gaussian HMM - soft posterior", "Logistic Regression",
            "Random Forest Classifier", "HistGradientBoostingClassifier",
        }
        assert expected_models.issubset(set(mean_comparison["model"]))

        mean_comparison["mean_DPA_%"] = 100 * mean_comparison["DPA_direction_accuracy"]
        display(
            mean_comparison[["model", "mean_DPA_%"]]
            .sort_values("mean_DPA_%", ascending=False)
            .round(2)
        )
        display(Image(filename=str(SUPERVISED_RUN / "dpa_comparison_all_assets.png")))
    ''').strip()

    # Add an explicit K=2/3/4 comparison for the central SPY case. This makes the
    # model-selection logic visible in the notebook instead of only stating K=4.
    section5_idx = find_markdown_index(nb, "## 5. SPY כמקרה מבחן")
    k_cells = [
        rtl_md(r'''
        ### בדיקה מפורשת של K=2,3,4 ב-SPY

        כדי לראות שהבחירה ב-\(K=4\) אינה רק label בדיעבד, נציג את המועמד בעל Validation log-likelihood הטוב ביותר עבור כל \(K\). `Val. LL / obs.` גבוה יותר (פחות שלילי) עדיף, ואילו BIC נמוך יותר עדיף. `Min occupancy` מזכיר שגם מודל עם likelihood טוב יכול ליצור state קטן מאוד.
        '''),
        code_cell(r'''
        spy_candidates = pd.read_csv(EXTENDED_RUN / "SPY" / "candidate_diagnostics.csv")
        best_idx = spy_candidates.groupby("k")["validation_log_likelihood_per_observation"].idxmax()
        spy_k_compare = spy_candidates.loc[best_idx, [
            "k", "seed", "validation_log_likelihood_per_observation",
            "bic_train", "min_state_occupancy_pct", "fit_time_sec",
        ]].sort_values("k").copy()
        spy_k_compare = spy_k_compare.rename(columns={
            "validation_log_likelihood_per_observation": "Val. LL / obs.",
            "bic_train": "BIC (Train)",
            "min_state_occupancy_pct": "Min occupancy %",
            "fit_time_sec": "Fit time sec",
        })
        display(spy_k_compare.round(3))

        with (EXTENDED_RUN / "SPY" / "selected_model_summary.json").open(encoding="utf-8") as f:
            spy_selected = json.load(f)
        print(
            f"Final SPY refit: K={spy_selected['selected_k']}, seed={spy_selected['selected_seed']}, "
            f"converged={spy_selected['final_fit_converged']}, "
            f"iterations={spy_selected['final_fit_iterations']}, "
            f"fit_time={spy_selected['final_fit_time_sec']:.2f}s"
        )
        '''),
        rtl_md(r'''
        ב-SPY גם Validation likelihood וגם BIC משתפרים כאשר עוברים מ-2 ל-4 states, ולכן \(K=4\) הוא בחירה סבירה לפי פרוטוקול הניסוי. עם זאת, ב-\(K=3\) וב-\(K=4\) קיים state קטן של כ-4% מה-Train, ולכן ממשיכים לבדוק seed stability ואת מאפייני ה-states לפני שמייחסים להם משמעות כלכלית.
        '''),
    ]
    nb.cells[section5_idx:section5_idx] = k_cells

    # DPA alone does not cover the numeric-return metrics promised in the project
    # plan. Add a compact SPY table from the same held-out artifact.
    section11_idx = find_markdown_index(nb, "## 11. Supervised ML Baselines")
    magnitude_cells = [
        rtl_md(r'''
        ### שגיאת magnitude על SPY

        DPA מתייחס רק לסימן. עבור המודלים שמחזירים תחזית מספרית לתשואה נשמרו גם MAE ו-RMSE על next-day log return ו-MAPE על מחיר הסגירה המשתמע. MAPE מוצג כמדד משלים בלבד, משום שמחיר מחר בדרך כלל קרוב למחיר היום ולכן הוא עלול להיראות טוב גם עבור Baseline פשוט.
        '''),
        code_cell(r'''
        spy_numeric = hmm_metrics.loc[
            hmm_metrics["asset"] == "SPY",
            ["model", "DPA_direction_accuracy", "MAE_return", "RMSE_return", "MAPE_price_%"],
        ].copy()
        spy_numeric["DPA_%"] = 100 * spy_numeric.pop("DPA_direction_accuracy")
        display(
            spy_numeric[["model", "DPA_%", "MAE_return", "RMSE_return", "MAPE_price_%"]]
            .round({"DPA_%": 2, "MAE_return": 5, "RMSE_return": 5, "MAPE_price_%": 3})
        )
        '''),
        rtl_md(r'''
        על SPY ה-hard וה-soft HMM כמעט זהים ל-Naive train-mean גם ב-MAE/RMSE/MAPE. כלומר גם כאשר עוברים מעבר לכיוון בלבד, אין כאן פער מעשי גדול לטובת ה-HMM. הדבר מחזק את הפרשנות שהערך המרכזי שלו בפרויקט הוא ייצוג מצב השוק ולא point forecast מדויק יותר.
        '''),
    ]
    nb.cells[section11_idx:section11_idx] = magnitude_cells

    nbformat.write(nb, NOTEBOOK)
    print(
        f"Patched {NOTEBOOK.name}: {len(REPLACEMENTS)} wording replacements, "
        "complete baseline comparison, K table, and magnitude metrics"
    )


if __name__ == "__main__":
    main()
